# Generated by Django 4.2.18 on 2025-01-16 16:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Brown Slippers', max_length=50),
            preserve_default=False,
        ),
    ]
