# Generated by Django 4.2.18 on 2025-01-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
